### ISSUE TITLE
erro php artisan migrator

### ISSUE THREAD

**Issue by felipeschmitz** [emtudo/school-api#2]
olá, estou tentando rodar no docker o comando "php artisan migrator" e gera o erro Illegal instruction.

o que está que está acontecendo?

**Comment by felipeschmitz** [comment]
[2018-09-25 20:13:33] local.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` bigint unsigned not null auto_increment primary key, `parent1_id` bigint unsigned null, `parent2_id` bigint unsigned null, `responsible1_id` bigint unsigned null, `responsible2_id` bigint unsigned null, `married_id` bigint unsigned null, `name` varchar(50) not null, `email` varchar(191) null, `country_register` varchar(11) null, `avatar_exten` varchar(4) null, `state_register` varchar(14) null, `state_register_state` char(2) null, `state_register_entity` varchar(4) null, `password` varchar(191) not null, `sex` enum('male', 'female') null, `birthdate` date not null, `address` json null, `phones` json null, `family_bag` tinyint(1) not null default '0', `natural_from` int unsigned null, `profession` varchar(191) null, `marital_status` enum('married', 'single', 'widower', 'divorced') null, `is_admin` tinyint(1) not null default '0', `master` tinyint(1) not null default '0', `last_tenant` int unsigned null, `documents` json null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` bigint unsigned not null auto_increment primary key, `parent1_id` bigint unsigned null, `parent2_id` bigint unsigned null, `responsible1_id` bigint unsigned null, `responsible2_id` bigint unsigned null, `married_id` bigint unsigned null, `name` varchar(50) not null, `email` varchar(191) null, `country_register` varchar(11) null, `avatar_exten` varchar(4) null, `state_register` varchar(14) null, `state_register_state` char(2) null, `state_register_entity` varchar(4) null, `password` varchar(191) not null, `sex` enum('male', 'female') null, `birthdate` date not null, `address` json null, `phones` json null, `family_bag` tinyint(1) not null default '0', `natural_from` int unsigned null, `profession` varchar(191) null, `marital_status` enum('married', 'single', 'widower', 'divorced') null, `is_admin` tinyint(1) not null default '0', `master` tinyint(1) not null default '0', `last_tenant` int unsigned null, `documents` json null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci') at /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists at /var/www/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists at /var/www/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141)
[stacktrace]
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('create table `u...', Array, Object(Closure))
#1 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('create table `u...', Array, Object(Closure))
#2 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(88): Illuminate\\Database\\Connection->statement('create table `u...')
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(264): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /var/www/app/app/Domains/Users/Database/Migrations/CreateUsersTable.php(69): Illuminate\\Database\\Schema\\Builder->create('users', Object(Closure))
#6 /var/www/app/vendor/artesaos/migrator/src/Migrator.php(176): Emtudo\\Domains\\Users\\Database\\Migrations\\CreateUsersTable->up()
#7 /var/www/app/vendor/artesaos/migrator/src/Migrator.php(146): Migrator\\Migrator->runUp('Emtudo\\\\Domains\\\\...', 2, false)
#8 /var/www/app/vendor/artesaos/migrator/src/Migrator.php(115): Migrator\\Migrator->runMigrationList(Array, Array)
#9 /var/www/app/vendor/artesaos/migrator/src/Console/MigrateCommand.php(66): Migrator\\Migrator->run(Array)
#10 /var/www/app/vendor/artesaos/migrator/src/Console/BaseCommand.php(12): Migrator\\Console\\MigrateCommand->fire()
#11 [internal function]: Migrator\\Console\\BaseCommand->handle()
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\\Container\\Container->call(Array)
#17 /var/www/app/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /var/www/app/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/app/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Migrator\\Console\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/app/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"}

**Comment by emtudo** [comment]
De acordo com o log, diz que a tabela já existe, tente:


php artisan migrator:fresh

**Comment by felipeschmitz** [comment]
Olá, rodei php artisan migrator:fresh e o erro permanece e não gerou nenhum erro adicional.

**Comment by emtudo** [comment]
Você está usando mysql 5.7? php 7.2?

Você configurou corretamente seu .env?

**Comment by felipeschmitz** [comment]
Sim, estou usando o docker-compose.yml que veio no projeto e os dados de acesso do banco pelo que vi são os mesmos.

O estranho é que no mysql ele cria as tabelas migrations, tenants, tenants_users e users.
